<?php
$this->headTitle('Link a client');
$this->headStyle()->appendStyle('div#body {
	width: 40em;
	margin: 1em auto;
}
label {
	font-weight: bold;
}
');
$this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js');
$this->inlineScript()->appendScript(<<<SCRIPT
$(document).ready(function() {
	$('pre[id^=pre_]').hide();
	$('select#sys_name').change(function() {
		$('pre[id^=pre_]').hide();
		var _sysName = $('select#sys_name option:selected').val();
		$('pre#pre_' + _sysName).show();
	});
});
SCRIPT
);
?>
	<div id="header">
		<h1>Link a Display UI Client</h1>
	</div>
	<div id="body">
		<p>This tool will provide you with the information needed to configure
		the Display UI Client software for this server.</p>
		<h3>Server URL</h3>
		<p>Please set the following line in the <code>[system]</code> section
		of <code>display_ui.ini</code>:</p>
		<pre>server_location=<?php echo $this->serverUrl() . $this->baseUrl(); ?></pre>
		<h3>Client Authentication</h3>
		<p>Each client connecting to the server has its own name, or <code>sys_name</code>,
		and a crytographically secure API key (<code>api_key</code>). Multiple installations
		<em>are</em> permitted to use the same system name and API key.</p>
		<label for="sys_name">Select a client:</label>
		<select name="sys_name" id="sys_name">
			<option></option>
<?php foreach($this->api_keys as $ak) {
	echo '			<option id="' . $ak[0] . '">' . $ak[0] . "</option>\n";
} ?>
		</select>
<?php foreach($this->api_keys as $ak) {
	echo '			<pre id="pre_' . $ak[0] . '">sys_name=' . $ak[0] . "\n";
	echo 'api_key=' . $ak[1] . "</pre>\n";
} ?>
		<p><a href="<?php echo $this->baseUrl(''); ?>">Return to the front page</a></p>
	</div>