<?php
$this->navActive = 'users';
$this->title = 'Users';
$this->headTitle('Users');
$this->headStyle()->appendStyle('#users-list {
	width: 100%;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}
#users-list td, #users-list th, #users-list {
	border-color: #aaaaaa;
}
#users-list tr.body {
	font-size: 123.1%;
	color: #383a3b;
}
#users-list th {
	background: #d1d1d1 url('.$this->baseUrl('images/widget-bg.png').') repeat-x;
	padding: 0.25em 0.5em;
	margin: 0;
	height: 1.5em; line-height: 1.25em;
	font-size: 123.1%;
	font-weight: bold;
	color: #333333;
	text-shadow: #ffffff 1px 1px 3px;
	cursor: pointer;
}
#users-list tr.body:nth-child(odd) { background-color: #fafafa; }
#users-list tr.body:hover { background-color: #ddeeff; }
td.id, th.id { width: 7.5%; }
td.username, th.username { width: 27.5%; }
td.email, th.email { width: 30%; }
td.last_active, th.last_active { width: 20%; }
td.acl_role, th.acl_role { width: 15%; }
#users-list td {
	padding: none;
	margin: none;
}
');
?>
<table cellspacing="0" id="users-list">
	<tr class="heading">
		<th class="id">ID</th>
		<th class="username">Username</th>
		<th class="email">Email</th>
		<th class="last_active">Last Active</th>
		<th class="acl_role">ACL Role</th>
	</tr>
<?php foreach($this->usersList as $u) { ?>
	<tr class="body">
		<td class="id"><?php echo $u['id']; ?></td>
		<td class="username"><?php echo $u['username']; ?></td>
		<td class="email"><?php echo $u['email']; ?></td>
		<td class="last_active"><?php echo $u['last_active']; ?></td>
		<td class="acl_role"><?php echo $u['acl_role']; ?></td>
	</tr>
<?php } ?>
</table>