<?php
$this->navActive = 'calendar';
$this->title = 'Add Event';
$this->headTitle('Add Event');
?>
<?php if($this->success) { ?>
<p><strong>Great! Your event was successfully added.</strong>
<a href="<?php echo $this->url(array(
			'module' => 'admin' ,
			'controller' => 'calendar' ,
			'action' => 'list'
		));	?>">Manage events or add another one?</a></p>
<?php } else { ?>
<p><strong>Whoops, there was a problem inserting the event into the database.</strong>
<a href="<?php echo $this->url(array(
			'module' => 'admin' ,
			'controller' => 'calendar' ,
			'action' => 'list'
		));	?>">Go back to managing the calendar.</a></p>
<?php } ?>