<?php
$this->navActive = 'weather';
$this->title = 'Manage Weather';
$this->headTitle('Weather');
$this->headStyle()->appendStyle('#clients-list {
	width: 100%;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}
#clients-list td, #clients-list th, #clients-list {
	border-color: #aaaaaa;
}
#clients-list tr.body {
	font-size: 123.1%;
	color: #383a3b;
}
#clients-list th {
	background: #d1d1d1 url('.$this->baseUrl('images/widget-bg.png').') repeat-x;
	padding: 0.25em 0.5em;
	margin: 0;
	height: 1.5em; line-height: 1.25em;
	font-size: 123.1%;
	font-weight: bold;
	color: #333333;
	text-shadow: #ffffff 1px 1px 3px;
	cursor: pointer;
}
#clients-list tr.body:nth-child(odd) { background-color: #fafafa; }
#clients-list tr.body:hover { background-color: #ddeeff; }
td.id, th.id { width: 10%; }
td.sys_name, th.sys_name { width: 50%; }
td.location, th.location { width: 30%; }
td.admin, th.admin { width: 20%; }
#clients-list td {
	padding: none;
	margin: none;
}
');
?>
<table cellspacing="0" id="clients-list">
	<tr class="heading">
		<th class="id">ID</th>
		<th class="sys_name">Client System Name</th>
		<th class="last_active">Location</th>
		<th class="admin">Administrator</th>
	</tr>
<?php foreach($this->clientsList as $c) { ?>
	<tr class="body">
		<td class="id"><?php echo $c['id']; ?></td>
		<td class="sys_name"><?php echo $c['sys_name']; ?></td>
		<td class="location" title="<?php echo $c['city']; ?>">
			<a href="<?php echo $c['link']; ?>"><?php echo $c['location']; ?></a>
		</td>
		<td class="admin"><?php echo $c['admin']; ?></td>
	</tr>
<?php } ?>
</table>