<?php
$layout = $this->layout();
// TODO: better relative/absolute URLs to our own stylesheets
$this->headLink()
	// first the YUI stylesheet
	->prependStylesheet('http://yui.yahooapis.com/combo?2.7.0/build/reset-fonts-grids/'
						.'reset-fonts-grids.css&amp;2.7.0/build/base/base-min.css')
	// now all of our styling
	->appendStylesheet('styles/dashboard.css')
	// and, for compatibility, some custom IE styles
	->appendStylesheet('styles/ie.css', NULL, TRUE);
$this->inlineScript()
	// our functionality-enabling code, will be externalized
	->appendScript('$j(document).ready(function () {
	DisplayUI.showSidebar();
	$j(\'li#sidebar-nav-logout\').click(function (event) {
		event.preventDefault();
		DisplayUI.logout();
	});
	$j(\'#hd a.logout\').click(function (event) {
		event.preventDefault();
		DisplayUI.logout();
	});
	$j(\'div.widgets-widget h2\').click(function (event) {
		event.preventDefault();
		DisplayUI.toggleWidget($j(this));
	});
});');
$this->headScript()
	// jQuery from Google's CDN first
	->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js')
	// give jQuery the $j alias
	->appendScript('var $j = jQuery.noConflict();')
	->appendFile('scripts/jquery.blockui.min.js')
	// our custom code for control panel functionality
	->appendFile('scripts/dui.core-functionality.js');
echo $this->doctype('XHTML1_STRICT');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headMeta(); ?>
</head>
<body>
<div id="doc2">
	<div id="hd">
		<span id="system-name"><?php echo $this->metadata->system_name; ?></span>
		<span id="top-howdy">Howdy, <a href="#" title="User profile"><?php echo $this->metadata->user_name; ?></a>
		&nbsp;&nbsp;|&nbsp;&nbsp;<a href="http://du.geekie.org/server/" title="Logout" class="logout">Logout</a></span>
	</div>
	<div id="bd" class="yui-t2">
		<div id="yui-main">
			<div class="yui-b">
				<h1><span><?php echo $this->title; ?></span></h1>
				<?php echo $layout->content; ?>
				<div class="clear"></div>
			</div>
		</div>
<?php echo $this->partial('admin-panel-navigation.phtml'); ?>
	</div>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>
