<?php $layout = $this->layout(); ?>
		<div class="yui-b" id="sidebar">
			<div id="sidebar-icon"> <a href="#" title="<?php echo $layout->metadata->system_name; ?>">Display UI Server</a> </div>
			<ul class="sidebar-nav">
				<li id="sidebar-nav-dashboard"<?php if($layout->navigation->is_dashboard) echo ' class="active"'; ?>><a href="#" title="Dashboard">Dashboard</a></li>
			</ul>
			<ul class="sidebar-nav">
				<li id="sidebar-nav-headlines"<?php if($layout->navigation->is_headlines) echo ' class="active"'; ?>><a href="#" title="Headlines">Headlines</a></li>
				<li id="sidebar-nav-multimedia"<?php if($layout->navigation->is_multimedia) echo ' class="active"'; ?>><a href="#" title="Media">Multimedia</a></li>
				<li id="sidebar-nav-weather"<?php if($layout->navigation->is_weather) echo ' class="active"'; ?>><a href="#" title="Weather">Weather</a></li>
				<li id="sidebar-nav-clients"<?php if($layout->navigation->is_clients) echo ' class="active"'; ?>><a href="#" title="Clients">Clients</a></li>
			</ul>
			<ul class="sidebar-nav">
				<li id="sidebar-nav-users"<?php if($layout->navigation->is_users) echo ' class="active"'; ?>><a href="#" title="Users">Users</a></li>
				<li id="sidebar-nav-options"<?php if($layout->navigation->is_options) echo ' class="active"'; ?>><a href="#" title="Options">Options</a></li>
				<li id="sidebar-nav-backup"<?php if($layout->navigation->is_backup) echo ' class="active"'; ?>><a href="#" title="Backup or restore">Backup</a></li>
			</ul>
			<ul class="sidebar-nav">
				<li id="sidebar-nav-logout"><a href="http://du.geekie.org/server/" title="Logout">Logout</a></li>
			</ul>
		</div>