<?php
$layout = $this->layout();
$this->logoutLink = $this->url(array('module' => 'admin', 'controller' => 'login', 'action' => 'logout'), 'login');
echo $this->doctype('XHTML1_STRICT');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php echo $this->headTitle('Display UI Server', 'PREPEND')->setSeparator(' | '); ?>

	<link href="<?php echo $this->baseUrl('styles/simple-blue.css'); ?>" rel="stylesheet" />
</head>
<body>
<div id="wrapper">
	<?php echo $layout->content; ?>
</div>
</body>
</html>