<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Display UI Server | Installer</title>
<style type="text/css">
<!--
body {
	margin: 0;
	padding: 0;
	background-color: #206080;
	font-family: Helvetica, Arial, sans-serif;
	font-size: 100%;
}
div {
	padding: 0;
	margin: 0;
}
p {
	line-height: 1.75;
	font-size: 0.875em;
	width: 40em;
	margin-top: 1.75em;
	margin-bottom: 1.75em;
}
table {
	font-size: 0.875em;
	line-height: 1.25;
	margin-bottom: 1.75em;
}
.underline {
	text-decoration: underline;
}
.good {
	color: #1E7B0D;
}
.bad {
	color: #900;
}
li {
	font-size: 0.875em;
	line-height: 1.75;
}
div.wrapper {
	background: #FEFEFE url(<?php echo $this->base_uri; ?>/images/installer/background.jpg) bottom right no-repeat;
	width: 920px;
	margin: 1em auto;
	padding: 10px;
	border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
}
div.wrapper#step1 {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/background-switch.jpg);
}
div#header {
	width: 880px;
	margin: 0 auto 2em auto;
}
div#body {
	width: 880px;
	margin: 1em auto;
}
div#header {
	border-bottom: 1px #444 solid;
}
div#footer {
	position: relative;
	top: 3em;
	width: 880px;
	color: #FEFEFE;
	margin-left: 1em;
}
h1 {
	font-family: Helvetica, Arial, sans-serif;
	font-weight: bold;
	text-transform: uppercase;
	font-size: 2.25em;
	margin: 1em 0;
}
h2, h3, h4, h5 {
	font-weight: bold;
}
h2 {
	font-size: 1.5em;
}
ul.requirements {
	list-style-type: circle;
}
span.mouseover {
	border-bottom: 1px #666 dashed;
}
small {
	font-size: 0.75em;
}
a.home, a.back, a.next {
	display: block;
	width: 88px; height: 89px;
	text-indent: -1000em;
}
a.home {
	background: none;
}
a.back {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/back.png);
}
a.next {
	margin-top: -89px;
	margin-left: 30em;
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/next.png);
}
p.notice.good {
	background-color: #c1f7a8;
	padding: 0.5em;
	color: #003c00;
}
p.notice.bad {
	padding: 0.5em;
	background-color: #f5afb0;
	color: #500000;
}
label {
	font-weight: bold;
}
p+input, p+select {
	margin-left: 10em;
	margin-top: -3.75em;
	width: 20em;
	font-family: Helvetica, Arial, sans-serif;
	padding: 0.5em;
	font-size: 0.875em;
	display: block;
}
-->
</style>
</head>
<body>
<div class="wrapper" id="step4">
	<div id="header">
		<h1><img src="<?php echo $this->base_uri; ?>/images/installer/title.png"
		width="670" height="35" alt="Display UI Server &raquo; Installer" /></h1>
	</div>
	<div id="body">
		<h2>Step 4 &raquo; Database</h2>
		<p>To hold data, authenticate users and client software, and prepare playlists,<br />
		the Display UI Server needs to connect to a database.</p>
		<p>Please supply the details of your database server.</p>
<?php if($this->uhoh) { ?>
		<p class="notice bad">Uh oh! The installer encountered problems connecting 
		to your database server.<br />Please check that everything is right.</p>
<?php } ?>
		<form id="databasedetails" action="<?php echo $this->base_uri; ?>/install/database/"
		method="post" accept-charset="utf-8">
			<div>
			<p><label for="hostname">Hostname</label></p>
				<input type="text" id="hostname" name="hostname"
				value="<?php if($this->hostname) echo $this->hostname; else echo 'localhost'; ?>" />
			<p><label for="username">Username</label></p>
				<input type="text" id="username" name="username"
				value="<?php if($this->username) echo $this->username; ?>" />
			<p><label for="password">Password</label></p>
				<input type="password" id="password" name="password"
				value="<?php if($this->password) echo $this->password; ?>" />
			<p><label for="dbname">Database Name</label></p>
				<input type="text" id="dbname" name="dbname"
				value="<?php if($this->dbname) echo $this->dbname; ?>" />
			<p><label for="driver">Database Adapter</label></p>
			<select name="driver" id="driver">
<?php if(extension_loaded('mysqli')) { ?>
				<option value="Mysqli">MySQLi</option>
<?php } if(extension_loaded('pdo_mysql')) { ?>
				<option value="Pdo_Mysql" selected="selected">PDO MySQL</option>
<?php } ?>
			</select>
			</div>
		</form>
		<p>This database should not be shared with other applications.</p>
		<a class="back" href="<?php echo $this->base_uri; ?>/install/config/"
		title="Return to Step 3">Back</a>
		<a class="next" href="#" title="Click here to submit the form">Next</a>
	</div>
	<div id="footer">
		<small>Display UI Server/<?php echo APPLICATION_VER; ?></small>
	</div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->base_uri; ?>/images/installer/jquery.qtip-1.0.0-rc3.min.js"></script>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
	$('p.notice').hide();
	setTimeout("$('p.notice').show('fold', {}, '500');", 500);
	$('a.next[title]').qtip({
		style: {
			name: 'light',
			tip: true
		}
	});
	$('a.back[title]').qtip({
		style: {
			name: 'light',
			tip: true
		}
	});
	$('a.next').effect('pulsate', {	times: 3 }, 2000);
});
$('a.next').click(function(e) {
	$('form#databasedetails').submit();
	e.preventDefault();
});
//]]>
</script>
</body>
</html>