<?php
$this->headTitle('Step 2');
$this->wrapperId = 'step2';
?>
	<div id="body">
		<h2>Step 2 &raquo; Testing</h2>
		<p>The installer has checked your system for compatibility requirements.</p>
		<p>Before we begin, make sure that your server meets these minimum requirements:<br />
		<small>Tip: mouse over any requirement to see a brief explanation.</small></p>

		<table width="500" border="0" cellspacing="2">
			<tr title="Zend Framework requires PHP 5.2 or above to function properly">
				<td>PHP version</td>
				<?php if($this->tests[0])
				echo '<td class="good">';
				else echo '<td class="bad" title="You\'ll need to upgrade PHP">';
				echo PHP_VERSION . '</td>'; ?>

			</tr>
			<tr title="Hash functions are used for cryptography, in securing this application">
				<td>Hash functions</td>
				<?php if($this->tests[1])
				echo '<td class="good">supported</td>';
				else echo '<td class="bad">not supported</td>'; ?>

			</tr>
			<tr title="cURL is used to fetch data for weather and headlines">
				<td>cURL</td>
				<?php if($this->tests[2])
				echo '<td class="good">supported</td>';
				else echo '<td class="bad">not supported</td>'; ?>

			</tr>
			<tr title="Sockets can be used instead of cURL">
				<td>Sockets</td>
				<?php if($this->tests[3])
				echo '<td class="good">supported</td>';
				else echo '<td class="bad">not supported</td>'; ?>

			</tr>
			<tr title="MySQLi is one way of connecting to the database">
				<td>MySQLi functions</td>
				<?php if($this->tests[4])
				echo '<td class="good">supported</td>';
				else echo '<td class="bad">not supported</td>'; ?>

			</tr>
			<tr title="PDO is the preferred driver for connecting to a database">
				<td>PHP Data Objects &amp; MySQL driver</td>
				<?php if($this->tests[5])
				echo '<td class="good">installed</td>';
				else echo '<td class="bad">not installed</td>'; ?>

			</tr>
			<tr title="APC helps to speed up the application when under load">
				<td>Alternative PHP Cache</td>
				<?php if($this->tests[6])
				echo '<td class="good">installed</td>';
				else echo '<td class="bad">not installed</td>'; ?>

			</tr>
			<tr title="We have to store the settings somewhere!">
				<td>Configuration files</td>
				<?php if($this->tests[7])
				echo '<td class="good">writable</td>';
				else echo '<td class="bad">not writable</td>'; ?>

			</tr>
			<tr title="Display UI stores some of the media in the filesystem">
				<td>Media storage</td>
				<?php if($this->tests[10])
				echo '<td class="good">writable</td>';
				else echo '<td class="bad">not writable</td>'; ?>

			</tr>
			<tr>
				<td>PHP safe mode</td>
				<?php if($this->tests[8])
				echo '<td class="good">disabled</td>';
				else echo '<td class="bad">enabled</td>'; ?>

			</tr>
			<tr>
				<td>Output buffering</td>
				<?php if($this->tests[9])
				echo '<td class="good">disabled</td>';
				else echo '<td class="bad">enabled</td>'; ?>

			</tr>
		</table>
<?php if(!$this->tests[10]) { ?>
		<p class="notice bad">Your media directory, located at
		<code><?php echo MEDIA_DIR; ?></code>,
		is not writable. Make it writable by setting its permissions to <code>0777</code>
		(grant every user write access) or contact your system administrator.</p>
<?php } if(!$this->tests[7]) { ?>
		<p class="notice bad">Your configuration directory, located at
		<code><?php echo CONFIG_DIR; ?></code>,
		is not writable. Make it writable by setting its permissions to <code>0777</code>
		(grant every user write access) or contact your system administrator.</p>
<?php } ?>
<?php if($this->fail >= 100) { ?>
		<p class="notice bad">It would appear that one or more of the essential
		requirements for running Display UI Server were not met.
		<span class="bad">The installer cannot continue.</span></p>
<?php } elseif($this->fail == 2) {
	$this->failed = ($this->tests[2]) ? 'Sockets' : 'cURL'; ?>
		<p class="notice">It would appear that a required component,
		<span class="underline"><?php echo $this->failed; ?></span>,
		is not available. However, the installer <em>can</em> continue
		since the backup dependency is available.</p>
<?php } elseif($this->fail == 3) {
	$this->failed = ($this->tests[4]) ? 'PDO/PDO_MySQL' : 'MySQLi'; ?>
		<p class="notice">It would appear that a required component,
		<span class="underline"><?php echo $this->failed; ?></span>,
		is not available. However, the installer <em>can</em> continue
		since the backup dependency is available.</p>
<?php } else { ?>
		<p class="notice good">Excellent! Your server set up meets the requirements
		to install Display UI Server.<br />Please click the arrow to continue.</p>
<?php } ?>
		<a class="back" href="<?php echo $this->url(array('controller' => 'install', 'action' => 'index')); ?>"
		title="Do you want to start over?">Start over</a>
<?php if($this->fail < 100) { ?>
		<a class="next" href="<?php echo $this->url(array('controller' => 'install', 'action' => 'config')); ?>"
		title="Click here to go to Step 3">Next</a>
<?php } ?>
	</div>
<?php $this->inlineScript()->appendScript('
$(document).ready(function(){
	$(\'tr[title]\').qtip({
		style: {
			name: \'dark\',
			tip: true
		}
	});
	$(\'p.notice\').hide();
	setTimeout("$(\'p.notice\').show(\'fold\', {}, \'500\');", 2500);
	$(\'a.next[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.back[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.next\').effect(\'pulsate\', {	times: 3 }, 2000);
});'); ?>