<?php
$this->navActive = 'multimedia';
$this->title = 'View Multimedia';
$this->headTitle('Multimedia');
if($this->canShow) {
?>
<p>Here's a preview of the content item with the media ID of <?php echo $this->id; ?>.</p>
<img src="data:<?php echo $this->mimeType; ?>;base64,<?php echo chunk_split(base64_encode($this->fileBinary)); ?>"
alt="<?php echo $this->id; ?>" style="max-width: 650px;" />
<?php } else { ?>
<h2>Oops, you can't preview that item.</h2>
<p>The media item with the ID of <?php echo $this->id; ?> is of the '<?php echo $this->type; ?>' type,
which cannot be previewed online.</p>
<?php } ?>
<p><a href="javascript:history.back(1);">Go back.</a></p>