<?php
$layout = $this->layout();
$this->inlineScript()
    ->prependFile($this->baseUrl('scripts/jquery.qtip-1.0.0-rc3.min.js'))
    ->prependFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js');
echo $this->doctype('XHTML1_STRICT');
$this->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('favicon.ico'),
'type' => 'image/x-icon', 'PREPEND'))
    ->prependStylesheet($this->baseUrl('styles/installer.css'));
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?php
	echo $this->headTitle('Installer', 'PREPEND')->setSeparator(' » ') . "\n";
	echo $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8')->setIndent('	') . "\n";
	echo $this->headLink()->setIndent('	') . "\n";
	echo $this->headStyle()->setIndent('	') . "\n";
	echo $this->headScript()->setIndent('	'); ?>
</head>
<body>
<div class="wrapper" id="<?php echo $this->wrapperId; ?>">
	<div id="header">
		<h1><img src="<?php echo $this->baseUrl('images/installer/title.png'); ?>"
		width="580" height="50" alt="Display UI Server &raquo; Installer" /></h1>
	</div>
	<?php echo $layout->content; ?>
	<div id="footer">
		<small>Display UI Server/<?php echo APPLICATION_VER; ?></small>
	</div>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>