<?php
$this->navActive = 'headlines';
$this->title = 'Manage Headlines';
$this->headTitle('Headlines');
$this->headStyle()->appendStyle('#headlines-list {
	width: 100%;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}
#headlines-list td, #headlines-list th, #headlines-list {
	border-color: #aaaaaa;
}
#headlines-list tr.body {
	font-size: 123.1%;
	color: #383a3b;
}
#headlines-list th {
	background: #d1d1d1 url('.$this->baseUrl('images/widget-bg.png').') repeat-x;
	padding: 0.25em 0.5em;
	margin: 0;
	height: 1.5em; line-height: 1.25em;
	font-size: 123.1%;
	font-weight: bold;
	color: #333333;
	text-shadow: #ffffff 1px 1px 3px;
	cursor: pointer;
}
#headlines-list tr.body:nth-child(odd) { background-color: #fafafa; }
#headlines-list tr.body:hover { background-color: #ddeeff; }
td.id, th.id { width: 7.5%; }
td.title, th.title { width: 47.5%; }
td.day, th.day { width: 5%; }
td.expires, th.expires { width: 15%; color: #666666; }
td.client, th.client { width: 17.5%; }
td.actions, th.actions { width: 7.5%; }
td.actions { font-size: 77%; }
td.actions a { border-bottom: none; margin: 0 0.25em; }
td.actions a:hover { border-bottom: inherit; }
td.actions a.delete { color: #bb2200; }
tr:hover td.expires, tr:hover td.active { color: inherit; }
#headlines-list td {
	padding: none;
	margin: none;
}
form { font-size: 123.1%; }
dd { margin-bottom: 1em; }
input { margin-right: 0.25em; }
label.optional { font-weight: normal; }
label.optional:after { content: " (optional)"; color: #666666; }
#addheadlinelink { color: inherit; }
#addheadlinelink.expanded:before { content: "- "; font-weight: normal; color: #666666; }
#addheadlinelink:not(.expanded):before { content: "+ "; font-weight: normal; color: #666666; }
form p.description { font-size: 75%; }
ul.errors {
	color: #bb2200;
}
#headlineinsert {
	margin: 1em auto;
	border: 1px #aaaaaa solid;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	width: 100%;
}
#headlinemessage {
	width: 95%;
}
td.day.day1 {
	background: #E7FFD1;
}
td.day.day2 {
	background: #FFD7C1;
}
div.ui-datepicker a { border-bottom: none; }
#dialog-confirm { display: none; text-align: left; font-size: 90%; }
.ui-widget-header a { border-bottom: none; }
');
$this->headLink()->appendStylesheet(
	$this->baseUrl('/styles/jquery-ui/jquery-ui-1.8.13.custom.css'));
$this->headScript()->appendFile(
	$this->baseUrl('/scripts/jquery-ui-1.8.13.custom.min.js'));
$this->inlineScript()->appendScript('$j(document).ready(function() {
	$j("#headlineinsert").hide();
	if(window.location.pathname.search(/insert-process/) != -1) {
		$j("#headlineinsert").show();
		$j("#addheadlinelink").addClass("expanded");
	}
	$j("#addheadlinelink").click(function(event) {
		event.preventDefault();
		$j("#headlineinsert").toggle("normal");
		$j(this).toggleClass("expanded");
	});
	DisplayUI.enableDatePicker("#headlineexpires");
	$j("a.delete").click(function(event) {
		event.preventDefault();
		var _id = $j(this).attr("id").replace("delete-href-","");
		$j("#dialog-confirm-id").text(_id);
		DisplayUI.ajaxDeleteObject(_id, "#dialog-confirm", "'
	. $this->url(array('module' => 'admin' , 'controller' => 'headlines' , 'action' => 'delete-process'))
	. '", "' . $this->csrf . '");
	});
});
');
?>
<h2><a href="#" id="addheadlinelink">Add a headline</a></h2>
<?php echo $this->insertForm; ?>
<table cellspacing="0" id="headlines-list">
	<tr class="heading">
		<th class="id">ID</th>
		<th class="title">Title</th>
		<th class="expires">Expires</th>
		<th class="day">Day</th>
		<th class="client">Client</th>
		<th class="actions"></th>
	</tr>
<?php foreach($this->headlinesList as $h) {
$h['active'] = ($h['active']) ? 'Yes' : 'No';
$h['delLink'] = $this->url(array(
		'module' => 'admin' ,
		'controller' => 'headlines' ,
		'action' => 'delete'
	)) . '?id='.$h['id'];
	?>
	<tr class="body">
		<td class="id"><?php echo $h['id']; ?></td>
		<td class="title"><?php echo $h['title']; ?></td>
		<td class="expires"><?php echo $h['expires']; ?></td>
		<td class="day day<?php echo $h['alternating']; ?>"><?php echo $h['alternating']; ?></td>
		<td class="client"><?php echo $h['sys_name']; ?></td>
		<td class="actions"><a href="<?php echo $h['delLink']; ?>"
			id="delete-href-<?php echo $h['id']; ?>" class="delete">Delete</a></td>
	</tr>
<?php } ?>
</table>
<div id="dialog-confirm" title="Delete this headline?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<strong>Are you sure you want to delete the headline with the ID of <span id="dialog-confirm-id"></span>?</strong></p>
	<p>Deletion is irreversible.</p>
</div>