<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"; "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Display UI Server | API for Weather</title>
</head>
<body>
<h1>An error occurred</h1>
<h2><?php echo $this->message; ?></h2>


<h3>Additional information:</h3>
<p><?php echo $this->explanation; ?></p>
</body>
</html>