<?php
$this->navActive = 'users';
$this->title = 'Users';
$this->headTitle('Users');
$this->headStyle()->appendStyle('#users-list {
	width: 100%;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}
#users-list td, #users-list th, #users-list {
	border-color: #aaaaaa;
}
#users-list tr.body {
	font-size: 123.1%;
	color: #383a3b;
}
#users-list th {
	background: #d1d1d1 url('.$this->baseUrl('images/widget-bg.png').') repeat-x;
	padding: 0.25em 0.5em;
	margin: 0;
	height: 1.5em; line-height: 1.25em;
	font-size: 123.1%;
	font-weight: bold;
	color: #333333;
	text-shadow: #ffffff 1px 1px 3px;
	cursor: pointer;
}
#users-list tr.body:nth-child(odd) { background-color: #fafafa; }
#users-list tr.body:hover { background-color: #ddeeff; }
td.id, th.id { width: 7.5%; }
td.username, th.username { width: 27.5%; }
td.email, th.email { width: 30%; }
td.last_active, th.last_active { width: 20%; }
td.acl_role, th.acl_role { width: 15%; }
td.delete, th.delete { width: 10%; }
#users-list td {
	padding: none;
	margin: none;
}
form { font-size: 123.1%; }
dd { margin-bottom: 1em; }
input { margin-right: 0.25em; }
label.optional { font-weight: normal; }
label.optional:after { content: " (optional)"; color: #666666; }
#adduserlink { color: inherit; }
#adduserlink.expanded:before { content: "- "; font-weight: normal; color: #666666; }
#adduserlink:not(.expanded):before { content: "+ "; font-weight: normal; color: #666666; }
form p.description { font-size: 75%; }
ul.errors {
	color: #bb2200;
}
#userinsert {
	margin: 1em auto;
	border: 1px #aaaaaa solid;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	width: 100%;
}
#dialog-confirm { display: none; text-align: left; font-size: 90%; }
.ui-widget-header a { border-bottom: none; }
');
$this->headLink()->appendStylesheet(
	$this->baseUrl('/styles/jquery-ui/jquery-ui-1.8.13.custom.css'));
$this->headScript()->appendFile(
	$this->baseUrl('/scripts/jquery-ui-1.8.13.custom.min.js'));
$this->inlineScript()->appendScript('$j(document).ready(function() {
	$j("#userinsert").hide();
	if(window.location.pathname.search(/insert-process/) != -1) {
		$j("#userinsert").show();
		$j("#adduserlink").addClass("expanded");
	}
	$j("#adduserlink").click(function(event) {
		event.preventDefault();
		$j("#userinsert").toggle("normal");
		$j(this).toggleClass("expanded");
	});
	$j("a.delete").click(function(event) {
		event.preventDefault();
		var _id = $j(this).attr("id").replace("delete-href-","");
		$j("#dialog-confirm-id").text(_id);
		DisplayUI.ajaxDeleteObject(_id, "#dialog-confirm", "'
	. $this->url(array('module' => 'admin' , 'controller' => 'users' , 'action' => 'delete-process'), null, true)
	. '", "' . $this->csrf . '");
	});
});
');
?>
<h2><a href="#" id="adduserlink">Add a user</a></h2>
<?php echo $this->insertForm; ?>
<table cellspacing="0" id="users-list">
	<tr class="heading">
		<th class="id">ID</th>
		<th class="username">Username</th>
		<th class="email">Email</th>
		<th class="last_active">Last Active</th>
		<th class="acl_role">Role</th>
		<th class="delete">Actions</th>
	</tr>
<?php foreach($this->usersList as &$u) {
$u['delete_link'] = $this->url(array('action' => 'delete', 'id' => $u['id']));
	?>
	<tr class="body">
		<td class="id"><?php echo $u['id']; ?></td>
		<td class="username"><?php echo $u['username']; ?></td>
		<td class="email"><?php echo $u['email']; ?></td>
		<td class="last_active"><?php echo $u['last_active']; ?></td>
		<td class="acl_role"><?php echo $u['acl_role']; ?></td>
		<td class="delete"><a href="<?php echo $u['delete_link']; ?>"
			class="delete" id="delete-href-<?php echo $u['id']; ?>">Delete</a></td>
	</tr>
<?php } ?>
</table>
<div id="dialog-confirm" title="Delete this user?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<strong>Are you sure you want to delete the user with the ID of <span id="dialog-confirm-id"></span>?</strong></p>
	<p>Deletion is irreversible.</p>
</div>