<?php
$this->wrapperId = ($this->status == -1) ? 'step3fail' : 'step3';
$this->headTitle('Step 3');
?>
	<div id="body">
<?php if($this->status == -1) { ?>
		<h2>Step 3 &raquo; Configuration</h2>
		<p class="notice bad">According to the system, the configuration file has already been set up.<br />
		The installer will not continue.</p>
		<p>Recommended actions: if you must force the installer to reconfigure the server,
		delete the <code>configuration.ini</code> file, typically located in <code>application/configs</code>.</p>
<?php } elseif($this->status == 1) { ?>
		<h2>Step 3 &raquo; Configuration</h2>
		<p class="notice good">Success! The system has set up your configuration file.</p>
		<p>Keep this secret server hash in a safe place:<br />
		<code><?php echo $this->secret; ?></code></p>
		<a class="back" href="<?php echo $this->url(array('controller' => 'install', 'action' => 'test')); ?>"
		title="Return to Step 2">Back</a>
		<a class="next" href="<?php echo $this->url(array('controller' => 'install', 'action' => 'database')); ?>"
		title="Click here to go to Step 4">Next</a>
<?php } ?>
	</div>
<?php $this->inlineScript()
	->appendScript('
$(document).ready(function(){
	$(\'p.notice\').hide();
	setTimeout("$(\'p.notice\').show(\'fold\', {}, \'500\');", 1000);
	$(\'a.next[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.back[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.next\').effect(\'pulsate\', {	times: 3 }, 2000);
});'); ?>