<?php
$this->wrapperId = 'step5';
$this->headTitle('Step 5');
?>
	<div id="body">
		<h2>Step 5 &raquo; Administrator User</h2>
		<p class="notice good">The installer succeeded in connecting to your database server<br />
		and setting up the structure of the tables.</p>
		<p>Just a tiny way to go now. Here you will set up the administrator user account
		that will manage the Display UI Server.</p>
<?php if($this->uhoh) { ?>
		<p class="notice bad">Uh oh! We couldn't use the data you submitted.<br />
		Please check that everything is right.</p>
<?php } ?>
		<form id="userdetails" action="<?php echo $this->url(array('controller' => 'install', 'action' => 'user')); ?>"
		method="post" accept-charset="utf-8">
			<div>
			<p id="usernamep"><label for="username">Username</label></p>
				<input type="text" id="username" name="username"
				value="<?php if($this->adminuser) echo $this->adminuser; else echo 'administrator'; ?>" />
			<p><label for="password">Password</label></p>
				<input type="password" id="password" name="password" />
			<p><label for="email">E-mail Address</label></p>
				<input type="text" id="email" name="email"
				value="<?php if($this->email) echo $this->email; ?>" />
			</div>
		</form>
		<p>This is the last step before you can get started with Display UI Server!</p>
		<a class="back" href="<?php echo $this->url(array('controller' => 'install', 'action' => 'database')); ?>"
		title="Return to Step 4">Back</a>
		<a class="next" href="#" title="Click here to submit the form">Next</a>
	</div>
<?php $this->inlineScript()
	->appendScript('
$(document).ready(function(){
	$(\'p.notice\').hide();
	setTimeout("$(\'p.notice\').show(\'fold\', {}, \'500\');", 500);
	$(\'p#usernamep\').qtip({
		style: {
			name: \'light\',
			tip: true
		},
		content: {
			text: \'We highly recommend that you keep the username as "administrator".\'
		}
	});
	$(\'input#username\').qtip({
		style: {
			name: \'light\',
			tip: true
		},
		content: {
			text: \'We highly recommend that you keep the username as "administrator".\'
		}
	});
	$(\'a.next[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.back[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.next\').effect(\'pulsate\', {	times: 3 }, 2000);
});
$(\'a.next\').click(function(e) {
	$(\'form#userdetails\').submit();
	e.preventDefault();
});'); ?>