<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Display UI Server | Installer</title>
<style type="text/css">
<!--
body {
	margin: 0;
	padding: 0;
	background-color: #206080;
	font-family: Helvetica, Arial, sans-serif;
	font-size: 100%;
}
div {
	padding: 0;
	margin: 0;
}
p {
	line-height: 1.75;
	font-size: 0.875em;
	width: 40em;
	margin-top: 1.75em;
	margin-bottom: 1.75em;
}
table {
	font-size: 0.875em;
	line-height: 1.25;
	margin-bottom: 1.75em;
}
.underline {
	text-decoration: underline;
}
.good {
	color: #1E7B0D;
}
.bad {
	color: #900;
}
li {
	font-size: 0.875em;
	line-height: 1.75;
}
div.wrapper {
	background: #FEFEFE;
	width: 920px;
	margin: 1em auto;
	padding: 10px;
	border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
}
div#header {
	width: 880px;
	margin: 0 auto 2em auto;
}
div#body {
	width: 880px;
	margin: 1em auto;
}
div#header {
	border-bottom: 1px #444 solid;
}
div#footer {
	position: relative;
	top: 3em;
	width: 880px;
	color: #FEFEFE;
	margin-left: 1em;
}
h1 {
	font-family: Helvetica, Arial, sans-serif;
	font-weight: bold;
	text-transform: uppercase;
	font-size: 2.25em;
	margin: 1em 0;
}
h2, h3, h4, h5 {
	font-weight: bold;
}
h2 {
	font-size: 1.5em;
}
ul.requirements {
	list-style-type: circle;
}
span.mouseover {
	border-bottom: 1px #666 dashed;
}
small {
	font-size: 0.75em;
}
a.home, a.back, a.next {
	display: block;
	width: 88px; height: 89px;
	text-indent: -1000em;
}
a.home {
	background: none;
}
a.back {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/back.png);
}
a.next {
	margin-top: -89px;
	margin-left: 30em;
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/next.png);
}
p.notice.good {
	background-color: #c1f7a8;
	padding: 0.5em;
	color: #003c00;
}
p.notice.bad {
	padding: 0.5em;
	background-color: #f5afb0;
	color: #500000;
}
code {
	font-family: Monaco, Consolas, monospace;
}
-->
</style>
</head>
<body>
<div class="wrapper" id="step4">
	<div id="header">
		<h1><img src="<?php echo $this->base_uri; ?>/images/installer/title.png"
		width="670" height="35" alt="Display UI Server &raquo; Installer" /></h1>
	</div>
	<div id="body">
		<h2>Step 4 &raquo; Database</h2>
		<p class="notice bad">According to the system, the database connection has already been set up.<br />
		The installer will not continue.</p>
		<p>Recommended actions: if you must force the installer to reconfigure the server,
		delete the <code>database.ini</code> file, typically located in <code>application/configs</code>.</p>
	</div>
	<div id="footer">
		<small>Display UI Server/<?php echo $this->version; ?></small>
	</div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->base_uri; ?>/images/installer/jquery.qtip-1.0.0-rc3.min.js"></script>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
	$('p.notice').hide();
	setTimeout("$('p.notice').show('fold', {}, '500');", 1000);
});
//]]>
</script>
</body>
</html>