<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Display UI Server | Installer</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->base_uri; ?>/images/installer/jquery.qtip-1.0.0-rc3.min.js"></script>
<style type="text/css">
<!--
body {
	margin: 0;
	padding: 0;
	background-color: #206080;
	font-family: Helvetica, Arial, sans-serif;
	font-size: 100%;
}
div {
	padding: 0;
	margin: 0;
}
p {
	line-height: 1.75;
	font-size: 0.875em;
	width: 40em;
	margin-top: 1.75em;
	margin-bottom: 1.75em;
}
table {
	font-size: 0.875em;
	line-height: 1.25;
	margin-bottom: 1.75em;
}
.underline {
	text-decoration: underline;
}
.good {
	color: #1E7B0D;
}
.bad {
	color: #900;
}
li {
	font-size: 0.875em;
	line-height: 1.75;
}
div.wrapper {
	background: #FEFEFE url(<?php echo $this->base_uri; ?>/images/installer/background.jpg) bottom right no-repeat;
	width: 920px;
	margin: 1em auto;
	padding: 10px;
	border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
}
div.wrapper#step1 {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/background-switch.jpg);
}
div#header {
	width: 880px;
	margin: 0 auto 2em auto;
}
div#body {
	width: 880px;
	margin: 1em auto;
}
div#header {
	border-bottom: 1px #444 solid;
}
div#footer {
	position: relative;
	top: 3em;
	width: 880px;
	color: #FEFEFE;
	margin-left: 1em;
}
h1 {
	font-family: Helvetica, Arial, sans-serif;
	font-weight: bold;
	text-transform: uppercase;
	font-size: 2.25em;
	margin: 1em 0;
}
h2, h3, h4, h5 {
	font-weight: bold;
}
h2 {
	font-size: 1.5em;
}
ul.requirements {
	list-style-type: circle;
}
span.mouseover {
	border-bottom: 1px #666 dashed;
}
small {
	font-size: 0.75em;
}
a.home, a.back, a.next {
	display: block;
	width: 48px;
	height: 48px;
	text-indent: -1000em;
}
a.home {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/home.png);
}
a.back {
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/back.png);
}
a.next {
	margin-top: -48px;
	margin-left: 30em;
	background-image: url(<?php echo $this->base_uri; ?>/images/installer/next.png);
}
p.notice.good {
	background-color: #c1f7a8;
	padding: 0.5em;
	color: #003c00;
}
p.notice.bad {
	padding: 0.5em;
	background-color: #f5afb0;
	color: #500000;
}
-->
</style>
<script type="text/javascript">
$(document).ready(function(){
    $('tr[title]').qtip({
        style: {
            name: 'dark',
            tip: true
        }
    });
});
</script>

</head>
<body>
<div class="wrapper" id="step2">
	<div id="header">
		<h1><img src="<?php echo $this->base_uri; ?>/images/installer/title.png"
		width="670" height="35" alt="Display UI Server &raquo; Installer" /></h1>
	</div>
	<div id="body">
		<h2>Step 2 &raquo; Testing</h2>
		<p>The installer has checked your system for compatibility requirements.</p>
		<p>Before we begin, make sure that your server meets these minimum requirements:<br />
		<small>Tip: mouse over any requirement to see a brief explanation.</small></p>
		
		<table width="500" border="0" cellspacing="2">
			<tr title="Zend Framework requires PHP 5.2 or above to function properly">
				<td>PHP version</td>
				<?php if($this->tests[0]) {
				echo '<td class="good">'; }
				else echo '<td class="bad" title="You\'ll need to upgrade PHP">';
				echo phpversion(); ?></td>
			</tr>
			<tr title="Hash functions are used for cryptography, in securing this application">
				<td>Hash functions</td>
				<?php if($this->tests[1])
				echo '<td class="good">supported';
				else echo '<td class="bad">not supported'; ?></td>
			</tr>
			<tr title="cURL is used to fetch data for weather and headlines">
				<td>cURL</td>
				<?php if($this->tests[2])
				echo '<td class="good">supported';
				else echo '<td class="bad">not supported'; ?></td>
			</tr>
			<tr title="Sockets can be used instead of cURL">
				<td>Sockets</td>
				<?php if($this->tests[3])
				echo '<td class="good">supported';
				else echo '<td class="bad">not supported'; ?></td>
			</tr>
			<tr title="MySQLi is one way of connecting to the database">
				<td>MySQLi functions</td>
				<?php if($this->tests[4])
				echo '<td class="good">supported';
				else echo '<td class="bad">not supported'; ?></td>
			</tr>
			<tr title="PDO is the preferred driver for connecting to a database">
				<td>PHP Data Objects &amp; MySQL driver</td>
				<?php if($this->tests[5])
				echo '<td class="good">installed';
				else echo '<td class="bad">not installed'; ?></td>
			</tr>
			<tr title="APC helps to speed up the application when under load">
				<td>Alternative PHP Cache</td>
				<?php if($this->tests[6])
				echo '<td class="good">installed';
				else echo '<td class="bad">not installed'; ?></td>
			</tr>
			<tr title="We have to store the settings somewhere!">
				<td>Configuration files</td>
				<?php if($this->tests[7])
				echo '<td class="good">writable';
				else echo '<td class="bad">not writable'; ?></td>
			</tr>
			<tr>
				<td>PHP safe mode</td>
				<?php if($this->tests[8])
				echo '<td class="good">disabled';
				else echo '<td class="bad">enabled'; ?></td>
			</tr>
			<tr>
				<td>Output buffering</td>
				<?php if($this->tests[9])
				echo '<td class="good">disabled';
				else echo '<td class="bad">enabled'; ?></td>
			</tr>
		</table>
<?php if($this->fail >= 100) { ?>
		<p class="notice bad">It would appear that one or more of the essential
		requirements for running Display UI Server were not met. 
		<span class="bad">The installer cannot continue.</span></p>
<?php } elseif($this->fail == 2) { 
	$this->failed = ($this->tests[2]) ? 'Sockets' : 'cURL'; ?>
		<p class="notice">It would appear that a required component, 
		<span class="underline"><?php echo $this->failed; ?></span>, 
		is not available. However, the installer <em>can</em> continue 
		since the backup dependency is available.</p>
<?php } elseif($this->fail == 3) {
	$this->failed = ($this->tests[4]) ? 'PDO/PDO_MySQL' : 'MySQLi'; ?>
		<p class="notice">It would appear that a required component, 
		<span class="underline"><?php echo $this->failed; ?></span>, 
		is not available. However, the installer <em>can</em> continue 
		since the backup dependency is available.</p>
<?php } else { ?>
		<p class="notice good">Excellent! Your server set up meets the requirements
		to install Display UI Server.<br />Please click the arrow to continue.</p>
<?php } ?>
		<a class="back" href="<?php echo $this->base_uri; ?>/install/">Start over</a>
<?php if($this->fail < 100) { ?>
		<a class="next" href="<?php echo $this->base_uri; ?>/install/config/">Next</a>
<?php } ?>
	</div>
	<div id="footer">
		<small>Display UI Server/<?php echo $this->version; ?></small>
	</div>
</div>
</body>
</html>