<?php
$this->navActive = 'multimedia';
$this->title = 'Upload Multimedia';
$this->headTitle('Upload Multimedia');
$this->headStyle()->appendStyle('form { font-size: 123.1%; }
dd { margin-bottom: 1em; }
input { margin-right: 0.25em; }
label.optional { font-weight: normal; }
label.optional:after { content: " (optional)"; color: #666666; }
#mediumtitle { width: 95%; }
#mediaupload {
	margin: 1em auto;
	border: 1px #aaaaaa solid;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	width: 75%;
}
form p.description, form p.hint { font-size: 75%; color: #666666; }
ul.errors {
	color: #bb2200;
}
#hideoptional { display: none; }
div.ui-datepicker a {
	border-bottom: none;
}
.ui-timepicker-div .ui-widget-header{ margin-bottom: 8px; }
.ui-timepicker-div dl{ text-align: left; }
.ui-timepicker-div dl dt{ height: 25px; }
.ui-timepicker-div dl dd{ margin: -25px 10px 10px 65px; }
.ui-timepicker-div td { font-size: 90%; }
');
$this->headLink()->appendStylesheet(
	$this->baseUrl('/styles/jquery-ui/jquery-ui-1.8.13.custom.css'));
$this->headScript()
	->appendFile($this->baseUrl('/scripts/jquery-ui-1.8.13.custom.min.js'))
	->appendFile($this->baseUrl('/scripts/jquery-ui.timepicker.min.js'));
$this->inlineScript()->appendScript('$j(document).ready(function() {
	$j(\'#mediumactivation-label, #mediumactivation-element\').hide();
	function toggleOptional () {
		$j(".optional").toggle(0, function() {
			$j("#" + $j(this).attr("for") + ":not(#mediumactivation)").parent().toggle();
		});
	}
	toggleOptional();
	$j(\'#mediumactivatenow-element input\').change(function() {
		var val = $j(\'#mediumactivatenow-element input:checked\').val();
		switch(val) {
			case \'0\':
				$j(\'#mediumactivation-label, #mediumactivation-element\').show(\'slide\');
				$j(\'#mediumactivation-label label\').removeClass(\'optional\');
				break;
			case \'1\':
				$j(\'#mediumactivation-label, #mediumactivation-element\').hide(\'slide\');
				$j(\'#mediumactivation-label label\').addClass(\'optional\');
		}
	});
	$j("#hideoptional").css("display", "inline").text("Show optional fields.").click(function(event) {
		event.preventDefault();
		toggleOptional();
		if($j(this).text() == "Hide optional fields.") $j(this).text("Show optional fields.");
		else $j(this).text("Hide optional fields.");
	});
	DisplayUI.enableDatePicker("#mediumactivation");
	DisplayUI.enableDatePicker("#mediumexpiration");
});');
?>
<p><strong>It's easy to upload a media file to the Display UI system.</strong> <a href="#" id="hideoptional">Hide optional fields.</a></p>
<?php
echo $this->form; ?>