<?php
$this->navActive = 'users';
$this->title = 'Users';
$this->headTitle('Users');
$this->headStyle()->appendStyle('#users-list {
	width: 100%;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}
#users-list td, #users-list th, #users-list {
	border-color: #aaaaaa;
}
#users-list tr.body {
	font-size: 123.1%;
	color: #383a3b;
}
#users-list th {
	background: #d1d1d1 url('.$this->baseUrl('images/widget-bg.png').') repeat-x;
	padding: 0.25em 0.5em;
	margin: 0;
	height: 1.5em; line-height: 1.25em;
	font-size: 123.1%;
	font-weight: bold;
	color: #333333;
	text-shadow: #ffffff 1px 1px 3px;
	cursor: pointer;
}
#users-list tr.body:nth-child(odd) { background-color: #fafafa; }
#users-list tr.body:hover { background-color: #ddeeff; }
td.id, th.id { width: 7.5%; }
td.username, th.username { width: 27.5%; }
td.email, th.email { width: 30%; }
td.last_active, th.last_active { width: 20%; }
td.acl_role, th.acl_role { width: 15%; }
#users-list td {
	padding: none;
	margin: none;
}
form { font-size: 123.1%; }
dd { margin-bottom: 1em; }
input { margin-right: 0.25em; }
label.optional { font-weight: normal; }
label.optional:after { content: " (optional)"; color: #666666; }
#adduserlink { color: inherit; }
#adduserlink.expanded:before { content: "- "; font-weight: normal; color: #666666; }
#adduserlink:not(.expanded):before { content: "+ "; font-weight: normal; color: #666666; }
form p.description { font-size: 75%; }
ul.errors {
	color: #bb2200;
}
#userinsert {
	margin: 1em auto;
	border: 1px #aaaaaa solid;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	width: 100%;
}
');
$this->inlineScript()->appendScript('$j(document).ready(function() {
	$j("#userinsert").hide();
	if(window.location.pathname.search(/insert-process/) != -1) {
		$j("#userinsert").show();
		$j("#adduserlink").addClass("expanded");
	}
	$j("#adduserlink").click(function(event) {
		event.preventDefault();
		$j("#userinsert").toggle("normal");
		$j(this).toggleClass("expanded");
	});
});
');
?>
<h2><a href="#" id="adduserlink">Add a user</a></h2>
<?php echo $this->insertForm; ?>
<table cellspacing="0" id="users-list">
	<tr class="heading">
		<th class="id">ID</th>
		<th class="username">Username</th>
		<th class="email">Email</th>
		<th class="last_active">Last Active</th>
		<th class="acl_role">ACL Role</th>
	</tr>
<?php foreach($this->usersList as $u) { ?>
	<tr class="body">
		<td class="id"><?php echo $u['id']; ?></td>
		<td class="username"><?php echo $u['username']; ?></td>
		<td class="email"><?php echo $u['email']; ?></td>
		<td class="last_active"><?php echo $u['last_active']; ?></td>
		<td class="acl_role"><?php echo $u['acl_role']; ?></td>
	</tr>
<?php } ?>
</table>