<?php
$layout = $this->layout();
$this->logoutLink = $this->url(
array(
	'module' => 'admin',
	'controller' => 'login',
	'action' => 'logout'), 'login');
echo $this->doctype('XHTML1_STRICT');
$this->headLink(
array(
	'rel' => 'icon',
	'href' => $this->baseUrl('favicon.ico'),
	'type' => 'image/x-icon',
	'PREPEND'))
	->prependStylesheet($this->baseUrl('styles/simple-blue.css'));
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php
	echo $this->headTitle('Display UI Server', 'PREPEND')->setSeparator(' | ');
	echo "\n";
	echo $this->headLink();
	echo "\n";
	echo $this->headStyle();
	echo "\n";
	echo $this->headScript(); ?>
</head>
<body>
<div id="wrapper">
	<?php echo $layout->content; ?>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>