<?php
$this->title = 'An error occurred';
$this->headTitle('An Error Occurred');
?>
<h2><?php echo $this->message; ?></h2>

<?php if ('development' == APPLICATION_ENV) : ?>

<h3>Exception information:</h3>
<p><strong>Message:</strong> <?php echo $this->exception->getMessage(); ?></p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString(); ?></pre>

<h3>Request Parameters:</h3>
<pre><?php var_dump($this->request->getParams()); ?></pre>

<?php endif; ?>