<?php
$this->navActive = 'users';
$this->title = 'Delete Users';
$this->headTitle('Users');
$this->headStyle()->appendStyle('input[type=submit] {
	margin-right: 0.5em;
}
#deleteline { display: none; }
');
$this->inlineScript()->appendScript('$j(document).ready(function() {
	$j("#deletesuccess").hide();
	$j("#deleteline").show();
	$j("#deleteline").ajaxForm({
		resetForm: false,
		target: "#deletesuccess",
		url : "'.$this->url(array('module' => 'admin' , 'controller' => 'users' , 'action' => 'delete-process'), null, true).'",
		beforeSubmit : function() {
			$j("#deleteline").block({
				message: "<img src=\''.$this->baseUrl('images/ajax-loader.gif').'\' />"
			});
		},
		success : function() {
			$j("#deleteline").unblock().empty();
			$j("#deletesuccess").show("slide");
		}
	});
});');
?>
<p><strong>Are you sure you want to delete the user with the ID of <?php echo $this->id; ?>?</strong></p>
<p>Deletion is irreversible and will remove the user entry from the database.
The only way to recover from accidental deletion is reverting to an older backup of the database and files.</p>
<form id="deleteline" action="" method="get">
<input type="hidden" name="id" id="deleteid" value="<?php echo $this->id; ?>" />
<input type="hidden" name="deletecsrf" id="deletecsrf" value="<?php echo $this->csrf; ?>" />
<p><input type="submit" name="deleteconf" id="deleteconf-1" value="Yes!" />
<input type="submit" name="deleteconf" id="deleteconf-0" value="No!" /></p>
</form>
<p id="deletesuccess"></p>
<noscript>
<p>You need JavaScript for deletion functionality to work.</p>
</noscript>