<?php
$this->wrapperId = 'step4';
$this->headTitle('Step 4');
?>
	<div id="body">
		<h2>Step 4 &raquo; Database</h2>
<?php if($this->status == -1) { ?>
		<p class="notice bad">According to the system, the database connection has already been set up.<br />
		The installer will not continue.</p>
		<p>Recommended actions: if you must force the installer to reconfigure the server,
		delete the <code>database.ini</code> file, typically located in <code>application/configs</code>.</p>
<?php } elseif($this->status == 1) { ?>
		<p class="notice bad">The installer encountered an error while setting up the structure
		of the database.</p>
		<p>Is the database clean? Although the installer could connect to the SQL server,
		it is possible that the database contains data from previous installs or other software.
		We recommend using a clean database for the installation.</p>
<?php } ?>
	</div>
<?php $this->inlineScript()->appendScript('
$(document).ready(function(){
	$(\'p.notice\').hide();
	setTimeout("$(\'p.notice\').show(\'fold\', {}, \'500\');", 1000);
});'); ?>