<?php
$this->wrapperId = "step1";
$this->headTitle('Installation Complete!');
?>
	<div id="body">
		<h2>You're done!</h2>
		<p>The installer has finished installing everything that the Display UI Server
		needs to run, including basic configuration, a database connection, and
		an administrator account.</p>
		<p>You can now visit the administration panel by clicking the next button below.
		And that will likely be the last time you see this installer interface
		(or the flashing arrow icon).</p>
		<p>We sincerely hope that the Display UI solution addresses your needs.</p>
		<a class="home" href="<?php echo $this->baseUrl(''); ?>">Home</a>
		<a class="next" href="<?php echo $this->baseUrl(''); ?>"
		title="Visit your installation!">Done</a>
	</div>
<?php $this->inlineScript()
	->appendScript('
$(document).ready(function(){
	$(\'a.next[title]\').qtip({
		style: {
			name: \'light\',
			tip: true
		}
	});
	$(\'a.next\').effect(\'pulsate\', { times: 3 }, 2000);
});'); ?>